POST http://localhost:5000/api/phones
Content-Type: application/json

{
    "brand": "Samsung",
    "model": "Galaxy A17 5G",
    "dateProduction": "2025-08-08"
}


GET http://localhost:5000/api/phones


GET http://localhost:5000/api/phones/68c662a862a83a8c2ee78f22



PATCH http://localhost:5000/api/phones/68c662a862a83a8c2ee78f22
Content-Type: application/json

{
    "model":"Galaxy A26 5G"
}



DELETE http://localhost:5000/api/phones/68c662a862a83a8c2ee78f22